name: moodlogger
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^6.1.0
  # Value equality
  equatable: ^1.2.5
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3
  # custom radio
  custom_radio: ^0.1.2
  # date picker
  calendar_strip: ^1.0.6
  # cupertino icons 
  cupertino_icons: ^0.1.3
  flutter_datetime_picker: ^1.3.8
  datetime_picker_formfield: ^1.0.0
  #custom_radio_grouped_button: ^1.0.1
  chips_choice: ^1.2.0
  grouped_list: ^3.2.2
  tinycolor: ^1.0.2
  scroll_to_index: ^1.0.6
  flutter_slidable: ^0.5.4
  table_calendar: ^2.2.3
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  font_awesome_flutter: ^8.8.1
  flutter_signin_button: ^1.0.0
  provider: ^4.3.1
  parse_server_sdk: ^1.0.26
  smart_select: ^3.0.2
  carousel_select_widget: ^0.1.0
  flutter_page_transition: ^0.1.6
  sticky_headers: ^0.1.8+1
  dio: ^3.0.10
  searchable_dropdown: ^1.1.3
  image_picker: ^0.6.7+7
  video_player: ^0.10.12+2
  #loading_overlay: ^0.2.1
  image_cropper: ^1.3.1
  carousel_slider: ^2.2.1
  cached_network_image: ^2.3.2+1
  auto_animated: ^2.1.0
  material_design_icons_flutter: ^4.0.5655
  video_trimmer: ^0.2.7
  uuid: ^2.2.2
  video_thumbnail: ^0.2.4
  #multi_image_picker: ^4.7.14
  flutter_absolute_path: ^1.0.6
  #multi_media_picker: ^0.2.3
  media_picker_builder: ^1.3.2
  visibility_detector: ^0.1.5
  drag_select_grid_view: ^0.3.1
  image: ^2.1.19
  path_provider: ^1.6.24
  cached_video_player: ^1.0.3
  mime: ^0.9.7
  palette_generator: ^0.2.3
  swipedetector: 1.2.0
  sliding_up_panel: ^1.0.2
  sliding_panel: ^1.3.2
  url_launcher: ^5.7.10
  flutter_wall_layout: ^1.0.0
  flutter_facebook_login: ^3.0.0
  invert_colors: ^0.0.2
  firebase_messaging: ^6.0.16
  flutter_material_color_picker: ^1.0.5
  numberpicker: ^2.0.1
  #onesignal_flutter: ^2.6.3
  flutter_local_notifications: ^4.0.1+2
  flutter_native_timezone: ^1.0.10
  flutter_test:
    sdk: flutter
  syncfusion_flutter_datepicker: ^19.1.56-beta
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  build_runner: ^1.11.1
  flutter_easyloading: ^3.0.0
  back_button_interceptor: ^5.0.0
  flutter_image_compress: ^1.0.0
  fluttertoast: ^8.0.7
  radial_button: ^0.1.1
  fab_circular_menu: ^1.0.2
  unicorndial: ^1.1.5
  scroll_app_bar: ^2.0.0
  flutter_video_info: ^1.2.0
  photo_view: ^0.12.0
  file_picker: ^1.6.3+2
  camera: ^0.5.0
  path: ^1.8.0
  flutter_staggered_animations: "^0.1.2"
  #auto_animated: ^3.0.0
dev_dependencies:
  hive_generator: ^0.8.2
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/loading_bar.gif
    - assets/smiley_face.png
    - assets/activity.png
    - assets/grey_abstract_geometric_triangle.jpg
    - assets/gray_circles_pattern.jpg
    - assets/gray_geometric_triangles_pattern.jpg
    - assets/honeycomb_pattern.jpg
    - assets/critical.png
    - assets/angry.png
    - assets/sad.png
    - assets/peaceful.png
    - assets/powerful.png
    - assets/scared.png
    - assets/joyful.png
    - assets/hurt.png
    - assets/hostile.png
    - assets/mad.png
    - assets/selfish.png
    - assets/hateful.png
    - assets/confused.png
    - assets/rejected.png
    - assets/helpless.png
    - assets/submissive.png
    - assets/insecure.png
    - assets/anxious.png
    - assets/excited.png
    - assets/energetic.png
    - assets/creative.png
    - assets/hopeful.png
    - assets/aware.png
    - assets/proud.png
    - assets/respected.png
    - assets/appreciated.png
    - assets/important.png
    - assets/faithful.png
    - assets/nurturing.png
    - assets/trusting.png
    - assets/loving.png
    - assets/intimate.png
    - assets/thoughtful.png
    - assets/content.png
    - assets/tired.png
    - assets/bored.png
    - assets/lonely.png
    - assets/depressed.png
    - assets/ashamed.png
    - assets/guilty.png
    - assets/app_icon.png


  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
